version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
clone_depth: 1
before_build:
- cmd: >-
    git submodule update --init --recursive

    mkdir Debug\plugins\ConEmu\Background

    mkdir Debug\plugins\ConEmu\Lines

    mkdir Debug\plugins\ConEmu\Thumbs
build:
  project: src\CE.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    call "%Configuration%\Tests_%Configuration%_%Platform%.exe"
deploy: off